### ISSUE TITLE
Padronização dos itens do menu

### ISSUE THREAD

**Issue by daneoshiga** [pythonbrasil/pythonbrasil-2019-site#19]
"keynotes e maiusculo e minusculo em lugares diferentes..

![image](https://user-images.githubusercontent.com/917634/61003090-77ce8f80-a339-11e9-8a1a-7c83e3cd4420.png)

**Comment by laylacodogno** [comment]
padronizei da seguinte forma: 
botões = minúsculos
títulos e links textuais = case sensitive
