### ISSUE TITLE
Adicionar twitter nas redes sociais

### ISSUE THREAD

**Issue by daneoshiga** [pythonbrasil/pythonbrasil-2019-site#26]
https://twitter.com/pythonbrasil/

**Comment by daneoshiga** [comment]
@laylacodogno eu acho que o #39 acabou sumindo com as redes sociais do evento..

**Comment by laylacodogno** [comment]
@daneoshiga não entendi exatamente onde que sumiu

**Comment by daneoshiga** [comment]
tudo certo nada errado.. olho curto q chama.
