### ISSUE TITLE
Adicionar nome da pessoa palestrante e sala

### ISSUE THREAD

**Issue by rougeth** [pythonbrasil/pythonbrasil-2019-site#73]
Na página https://2019.pythonbrasil.org.br/grade/, precisamos adicionar um popup com o nome da pessoa palestrante e sala em que a palestra/tutorial for acontecer. O popup foi a melhor forma que pensei para adicionar essas informações.

FullCalendar fornece um exemplo usando Tooltip.js que parece ser ideal: https://fullcalendar.io/docs/event-tooltip-demo

Os nomes e salas vêem por meio do atributo `extendedProps` ([referência: final da página](https://fullcalendar.io/docs/google-calendar), já que estamos usando o Google Calendar como fonte dos eventos.

Eu tentei acessar as propriedades, mas JS não me ajudou nessa. Conferindo a resposta do Google Calendar, as `extendedProps` estão chegando como previsto:

<img width="208" alt="Screen Shot 2019-10-09 at 00 15 31" src="https://user-images.githubusercontent.com/431892/66440199-bf8cb200-ea21-11e9-9989-2230697cf711.png">

Talvez eu não tenha visto alguma configuração necessária.

**Comment by mawkee** [comment]
Aparentemente ele não carrega as extended properties que são private, apenas as shared -- https://github.com/rougeth/calendaryo/issues/7

Fora isso, isso não resolve muito para mobile, resolve?

**Comment by mawkee** [comment]
Estou tentando implementar, se tiver ideias em relação a como fazer em mobile, sou todo ouvidos

**Comment by mawkee** [comment]
Correção, funciona muito bem pra mobile (quiçá melhor do que no desktop)

**Comment by rougeth** [comment]
@mawkee vc viu algo na documentação do FullCalendar sobre isso? Pq a requisição pro Google Calendar é feita e os extendedProps, mesmo private, chegam normalmente. Aquele print ali é da requisição que a página fez (não estava logado no Google). A diferença entre *private* e *shared* não parece ser de permissão de acesso:

Private:
> Properties that are private to the copy of the event that appears on this calendar.

Shared:
> Properties that are shared between copies of the event on other attendees' calendars.
